name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Lint code using SwiftLint ## Adds swift-linting to GH actions
      run: swiftlint lint --reporter github-actions-logging
    ## - name: Run tests
      ## run: swift test -v
